<?php
declare(strict_types=1);

/**
 * V4_Batch_Build_Page — Build V4 pages from atomic tree JSON.
 *
 * Registers two abilities:
 *   1. v4-batch-build-page    — Creates/rebuilds an Elementor page from a
 *      complete V4 atomic widget tree. Handles page creation, content setting,
 *      and cache invalidation in a single call.
 *   2. v4-set-elementor-content — Sets Elementor content on an existing page
 *      (direct _elementor_data write with cache purge).
 *
 * Architecture: Replaces the legacy adrians-batch-build-page and
 * adrians-set-v4-content patterns with V4-native tree handling.
 * Works with trees generated by framer-v4-pipeline (convert-xml-to-v4).
 *
 * @package Novamira_AdrianV2
 * @since   1.8.0
 */

namespace Novamira\AdrianV2\Abilities\V4Management;

use Novamira\AdrianV2\Helpers\Elementor_Version_Resolver;
use Novamira\AdrianV2\Helpers\Elementor_Data_Helpers;
use Novamira\AdrianV2\Helpers\Ability_Registry;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Static ability registrar for V4 batch page building.
 */
class V4_Batch_Build_Page {
    use Elementor_Data_Helpers;
    use Ability_Registry;

    /** @var string[] */
    private static array $ability_names = [];

    /**
     * Maximum element tree depth for validation (safety limit).
     */
    private const MAX_TREE_DEPTH = 50;

    /**
     * Maximum element count for validation.
     */
    private const MAX_ELEMENT_COUNT = 5000;

    /**
     * Register both abilities.
     */
    public static function register(): void {
        self::register_batch_build_page();
        self::register_set_elementor_content();
    }

    // =========================================================================
    // v4-batch-build-page
    // =========================================================================

    private static function register_batch_build_page(): void {
        $name = 'novamira-adrianv2/v4-batch-build-page';
        self::$ability_names[] = $name;

        wp_register_ability($name, [
            'label'               => __('V4 Batch Build Page', 'novamira-adrianv2'),
            'description'         => __(
                'Creates or rebuilds an Elementor page from a complete V4 atomic widget tree. '
                . 'The tree must be an array of V4 atomic elements (e-flexbox, e-div-block, '
                . 'e-heading, e-paragraph, e-button, e-image, etc.) with proper $$type-wrapped '
                . 'settings and styles. If post_id is omitted, a new draft page is created. '
                . 'Returns the post_id, element count, and validation summary.',
                'novamira-adrianv2'
            ),
            'category'            => 'adrianv2-v4-management',
            'execute_callback'    => [self::class, 'execute_batch_build_page'],
            'permission_callback' => 'novamira_permission_callback',
            'input_schema'        => [
                'type'       => 'object',
                'properties' => [
                    'content'  => [
                        'type'        => 'array',
                        'items'       => ['type' => 'object'],
                        'description' => __('V4 atomic element tree (array of elements).', 'novamira-adrianv2'),
                    ],
                    'post_id'  => [
                        'type'        => 'integer',
                        'description' => __('Existing post ID. Omit to create a new page.', 'novamira-adrianv2'),
                    ],
                    'title'    => [
                        'type'        => 'string',
                        'default'     => 'V4 Built Page',
                        'description' => __('Page title (for new pages only).', 'novamira-adrianv2'),
                    ],
                    'status'   => [
                        'type'        => 'string',
                        'enum'        => ['draft', 'publish', 'pending'],
                        'default'     => 'draft',
                        'description' => __('Post status.', 'novamira-adrianv2'),
                    ],
                    'validate' => [
                        'type'        => 'boolean',
                        'default'     => true,
                        'description' => __('Validate tree structure before saving.', 'novamira-adrianv2'),
                    ],
                ],
                'required'   => ['content'],
            ],
            'output_schema'       => [
                'type'       => 'object',
                'properties' => [
                    'post_id'        => ['type' => 'integer'],
                    'title'          => ['type' => 'string'],
                    'element_count'  => ['type' => 'integer'],
                    'status'         => ['type' => 'string'],
                    'permalink'      => ['type' => 'string'],
                    'validation'     => ['type' => 'object'],
                    'created'        => ['type' => 'boolean'],
                ],
            ],
            'meta'                => [
                'annotations'  => ['readonly' => false, 'destructive' => true, 'idempotent' => false],
                'show_in_rest' => true,
                'mcp'          => ['public' => true],
            ],
        ]);
    }

    /**
     * Execute v4-batch-build-page.
     *
     * @param array|null $input
     * @return array|\WP_Error
     */
    public static function execute_batch_build_page($input = null) {
        $input   = $input ?? [];
        $content  = $input['content'] ?? [];
        $post_id  = (int) ($input['post_id'] ?? 0);
        $title    = sanitize_text_field((string) ($input['title'] ?? 'V4 Built Page'));
        $status   = sanitize_text_field((string) ($input['status'] ?? 'draft'));
        $validate = (bool) ($input['validate'] ?? true);

        if (!is_array($content) || empty($content)) {
            return new \WP_Error('empty_content', __('Content tree must be a non-empty array of elements.', 'novamira-adrianv2'));
        }

        // Validate tree structure.
        $validation = ['valid' => true, 'issues' => [], 'stats' => []];
        if ($validate) {
            $validation = self::validate_tree($content);
            if (!$validation['valid']) {
                return new \WP_Error(
                    'validation_failed',
                    sprintf(
                        __('Tree validation failed: %d issue(s). See validation field for details.', 'novamira-adrianv2'),
                        count($validation['issues'])
                    ),
                    ['validation' => $validation]
                );
            }
        }

        $created = false;

        // Create or verify the page.
        if ($post_id > 0) {
            $post = get_post($post_id);
            if (!$post) {
                return new \WP_Error('post_not_found', "Post $post_id not found.");
            }

            // V4 guard: existing page must be Elementor-ready.
            if (!Elementor_Version_Resolver::site_is_v4()) {
                return new \WP_Error(
                    'v4_required',
                    sprintf(
                        __('V4 batch build requires Elementor 4.0+. Detected: %s.', 'novamira-adrianv2'),
                        Elementor_Version_Resolver::site_version_string()
                    )
                );
            }
        } else {
            $post_id = wp_insert_post([
                'post_title'   => $title,
                'post_type'    => 'page',
                'post_status'  => $status,
                'post_content' => '',
            ], true);

            if (is_wp_error($post_id)) {
                return $post_id;
            }
            $created = true;
        }

        // Set Elementor edit mode and version.
        update_post_meta($post_id, '_elementor_edit_mode', 'builder');
        if (defined('ELEMENTOR_VERSION')) {
            update_post_meta($post_id, '_elementor_version', ELEMENTOR_VERSION);
        }

        // Save the tree.
        $save = self::write_page($post_id, $content);
        if (is_wp_error($save)) {
            return $save;
        }

        $permalink = get_permalink($post_id) ?: '';

        return [
            'post_id'       => $post_id,
            'title'         => get_the_title($post_id),
            'element_count' => $validation['stats']['total_elements'] ?? count($content),
            'status'        => get_post_status($post_id),
            'permalink'     => $permalink,
            'validation'    => $validation,
            'created'       => $created,
            'summary'       => sprintf(
                '%s page %d with %d elements.',
                $created ? 'Created' : 'Rebuilt',
                $post_id,
                $validation['stats']['total_elements'] ?? count($content)
            ),
        ];
    }

    /**
     * Validate a V4 element tree structure.
     *
     * Checks: max depth, max count, required fields, style-class bindings.
     *
     * @param array $elements
     * @return array{valid: bool, issues: array, stats: array}
     */
    private static function validate_tree(array $elements): array {
        $issues = [];
        $stats  = ['total_elements' => 0, 'max_depth' => 0, 'widget_types' => []];

        $walk = function (array $nodes, int $depth) use (&$walk, &$issues, &$stats): void {
            foreach ($nodes as $node) {
                if (!is_array($node)) {
                    $issues[] = ['type' => 'invalid_node', 'message' => 'Element is not an array.'];
                    continue;
                }

                $stats['total_elements']++;

                if ($stats['total_elements'] > self::MAX_ELEMENT_COUNT) {
                    $issues[] = [
                        'type'    => 'too_many_elements',
                        'message' => sprintf(
                            'Tree exceeds %d elements (safety limit). Split into multiple pages.',
                            self::MAX_ELEMENT_COUNT
                        ),
                    ];
                    return;
                }

                if ($depth > self::MAX_TREE_DEPTH) {
                    $issues[] = [
                        'type'    => 'too_deep',
                        'message' => sprintf(
                            'Tree exceeds max depth of %d at element %s.',
                            self::MAX_TREE_DEPTH,
                            $node['id'] ?? 'unknown'
                        ),
                    ];
                    return;
                }

                $stats['max_depth'] = max($stats['max_depth'], $depth);

                // Track widget types.
                $wt = $node['widgetType'] ?? $node['elType'] ?? 'unknown';
                $stats['widget_types'][$wt] = ($stats['widget_types'][$wt] ?? 0) + 1;

                // Check required fields.
                if (empty($node['id'])) {
                    $issues[] = ['type' => 'missing_id', 'message' => 'Element missing required "id" field.'];
                }
                if (empty($node['elType'])) {
                    $issues[] = [
                        'type'    => 'missing_elType',
                        'message' => sprintf('Element %s missing required "elType" field.', $node['id'] ?? 'unknown'),
                    ];
                }

                // Check for known V4 atomic types.
                $valid_types = [
                    'widget', 'container', 'e-flexbox', 'e-div-block',
                    'e-heading', 'e-paragraph', 'e-button', 'e-image',
                    'e-svg', 'e-divider', 'e-youtube', 'e-self-hosted-video',
                ];
                if (!empty($node['elType']) && !empty($node['widgetType'])) {
                    if (!in_array($node['elType'], ['widget', 'container', 'e-flexbox', 'e-div-block'], true)
                        && !in_array($node['widgetType'], $valid_types, true)) {
                        $issues[] = [
                            'type'    => 'unknown_type',
                            'message' => sprintf(
                                'Element %s has unknown type elType=%s widgetType=%s.',
                                $node['id'] ?? 'unknown',
                                $node['elType'],
                                $node['widgetType']
                            ),
                        ];
                    }
                }

                // Recurse into children.
                $children = $node['elements'] ?? [];
                if (!empty($children) && is_array($children)) {
                    $walk($children, $depth + 1);
                }
            }
        };

        $walk($elements, 0);

        return [
            'valid'  => empty($issues),
            'issues' => $issues,
            'stats'  => $stats,
        ];
    }

    // =========================================================================
    // v4-set-elementor-content
    // =========================================================================

    private static function register_set_elementor_content(): void {
        $name = 'novamira-adrianv2/v4-set-elementor-content';
        self::$ability_names[] = $name;

        wp_register_ability($name, [
            'label'               => __('V4 Set Elementor Content', 'novamira-adrianv2'),
            'description'         => __(
                'Sets Elementor content on an existing page via direct _elementor_data '
                . 'write with cache purge. This is the V4-native equivalent of '
                . 'elementor-set-content for atomic trees. Pass the full element tree '
                . 'as the content field. Clears Elementor CSS cache automatically.',
                'novamira-adrianv2'
            ),
            'category'            => 'adrianv2-v4-management',
            'execute_callback'    => [self::class, 'execute_set_elementor_content'],
            'permission_callback' => 'novamira_permission_callback',
            'input_schema'        => [
                'type'       => 'object',
                'properties' => [
                    'post_id' => [
                        'type'     => 'integer',
                        'description' => __('Target post ID.', 'novamira-adrianv2'),
                    ],
                    'content' => [
                        'type'     => 'array',
                        'description' => __('V4 element tree to save.', 'novamira-adrianv2'),
                    ],
                ],
                'required'   => ['post_id', 'content'],
            ],
            'output_schema'       => [
                'type'       => 'object',
                'properties' => [
                    'success'       => ['type' => 'boolean'],
                    'post_id'       => ['type' => 'integer'],
                    'element_count' => ['type' => 'integer'],
                ],
            ],
            'meta'                => [
                'annotations'  => ['readonly' => false, 'destructive' => true, 'idempotent' => false],
                'show_in_rest' => true,
                'mcp'          => ['public' => true],
            ],
        ]);
    }

    /**
     * Execute v4-set-elementor-content.
     *
     * @param array|null $input
     * @return array|\WP_Error
     */
    public static function execute_set_elementor_content($input = null) {
        $input   = $input ?? [];
        $post_id = (int) ($input['post_id'] ?? 0);
        $content = $input['content'] ?? [];

        if ($post_id <= 0) {
            return new \WP_Error('invalid_post', __('Valid post_id required.', 'novamira-adrianv2'));
        }

        if (!is_array($content)) {
            return new \WP_Error('invalid_content', __('Content must be an array of elements.', 'novamira-adrianv2'));
        }

        $post = get_post($post_id);
        if (!$post) {
            return new \WP_Error('post_not_found', "Post $post_id not found.");
        }

        // Ensure Elementor edit mode.
        update_post_meta($post_id, '_elementor_edit_mode', 'builder');

        // Save.
        $save = self::write_page($post_id, $content);
        if (is_wp_error($save)) {
            return $save;
        }

        return [
            'success'       => true,
            'post_id'       => $post_id,
            'element_count' => count($content),
            'summary'       => sprintf(
                'Set %d elements on post %d. Cache purged.',
                count($content),
                $post_id
            ),
        ];
    }
}
