<?php
// SPDX-FileCopyrightText: 2026 Ovation S.r.l. <dev@novamira.ai>
// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

/**
 * Local_Styles_Renderer — Frontend inline-CSS workaround for Elementor 4.1.x.
 *
 * PROBLEM (Elementor 4.1.x bug):
 * The action `elementor/atomic-widgets/styles/register` is never fired during
 * frontend rendering. The Atomic_Global_Styles pipeline therefore never runs,
 * meaning `.e-{class_id}` selectors generated by the Atomic Widget renderer
 * exist in the DOM but have zero CSS backing them. Heading fonts, background
 * colours, padding — all invisible.
 *
 * WHAT THIS CLASS DOES:
 * Hooks into `wp_head` (priority 100, after Elementor enqueues its own head
 * output). Reads `_elementor_data` directly from the DB for the queried post,
 * walks the full element tree, collects every `element.styles` map, and emits
 * an inline `<style id="novamira-atomic-styles">` block with one CSS rule per
 * style-variant.
 *
 * PROP → CSS MAPPING (prop_to_css()):
 *  $$type "global-color-variable"  →  var(--e-gv-{id})
 *  $$type "color"                  →  #HEX  (or rgba/hsl as stored)
 *  $$type "size"                   →  {n}{unit}   e.g. 16px
 *  $$type "dimensions"             →  {t}{u} {r}{u} {b}{u} {l}{u}
 *                                     (logical: block-start → top, etc.)
 *  $$type "string"                 →  raw value  (font-family, flex-dir, …)
 *  all others                      →  (skipped)
 *
 * SELECTOR FORMAT:
 * Elementor's Atomic Widget renderer adds classes whose names ARE the style-ID
 * as stored in `element.styles` keys.  If the key already starts with "e-" we
 * use it verbatim; otherwise we prepend "e-" to match the HTML output.
 *
 * DISABLE GATE:
 * The renderer is a stopgap. When ELEMENTOR_VERSION ≥ 4.2.0 (the version
 * where the native pipeline is expected to work) `register()` exits early and
 * no hook is added.  The gate can also be controlled via the filter
 * `novamira_adrianv2/local_styles_renderer/enabled` (bool).
 *
 * @package Novamira_AdrianV2
 * @since   1.2.0
 */

namespace Novamira\AdrianV2\Helpers;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Renders inline `<style>` CSS for Atomic Widget local-style-class definitions.
 *
 * @since 1.2.0
 */
final class Local_Styles_Renderer {

	/**
	 * First Elementor version where the native Atomic CSS pipeline is known to
	 * work correctly in the frontend (= when this workaround should auto-disable).
	 */
	private const ELEMENTOR_NATIVE_CSS_MIN_VERSION = '4.2.0';

	/**
	 * Register the wp_head hook when the workaround is needed.
	 *
	 * Call this once from plugins_loaded / the helpers bootstrap.
	 * Does nothing on Elementor 4.2+ or when the filter disables it.
	 *
	 * @return void
	 */
	public static function register(): void {
		// Disable gate: skip automatically on Elementor ≥ 4.2.
		if ( self::native_pipeline_available() ) {
			return;
		}

		/**
		 * Allow operators to explicitly enable or disable the workaround.
		 *
		 * @param bool $enabled Whether to render inline atomic styles. Default true.
		 */
		$enabled = (bool) apply_filters( 'novamira_adrianv2/local_styles_renderer/enabled', true );
		if ( ! $enabled ) {
			return;
		}

		add_action( 'wp_head', array( self::class, 'render_inline_styles' ), 100 );
	}

	// -------------------------------------------------------------------------
	// Disable gate
	// -------------------------------------------------------------------------

	/**
	 * Returns true when Elementor's own Atomic CSS pipeline works in the
	 * frontend (Elementor ≥ 4.2.0), meaning our workaround is not needed.
	 *
	 * @return bool
	 */
	private static function native_pipeline_available(): bool {
		if ( ! defined( 'ELEMENTOR_VERSION' ) ) {
			return false;
		}
		return version_compare( (string) ELEMENTOR_VERSION, self::ELEMENTOR_NATIVE_CSS_MIN_VERSION, '>=' );
	}

	// -------------------------------------------------------------------------
	// wp_head callback
	// -------------------------------------------------------------------------

	/**
	 * Read _elementor_data, collect element.styles, emit inline <style>.
	 *
	 * Hooked into wp_head at priority 100.
	 *
	 * @return void
	 */
	public static function render_inline_styles(): void {
		// Only run on singular posts / pages.
		if ( ! is_singular() ) {
			return;
		}

		$post_id = (int) get_queried_object_id();
		if ( $post_id <= 0 ) {
			return;
		}

		// Read _elementor_data directly — avoids any wp_unslash corruption.
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery
		global $wpdb;
		$raw = $wpdb->get_var(
			$wpdb->prepare(
				"SELECT meta_value FROM {$wpdb->postmeta}
				 WHERE post_id = %d AND meta_key = '_elementor_data'
				 LIMIT 1",
				$post_id
			)
		);

		if ( ! $raw || ! is_string( $raw ) || '' === trim( $raw ) ) {
			return;
		}

		$data = json_decode( $raw, true );
		if ( ! is_array( $data ) || empty( $data ) ) {
			return;
		}

		// Walk the element tree and collect all style definitions.
		$all_styles = array();
		self::collect_styles( $data, $all_styles );

		if ( empty( $all_styles ) ) {
			return;
		}

		// Build CSS blocks.
		$css_blocks = array();
		foreach ( $all_styles as $style_id => $style_def ) {
			if ( ! is_string( $style_id ) || ! is_array( $style_def ) ) {
				continue;
			}
			$block = self::render_style_def( $style_id, $style_def );
			if ( '' !== $block ) {
				$css_blocks[] = $block;
			}
		}

		if ( empty( $css_blocks ) ) {
			return;
		}

		// Output — escaped as a raw CSS block (no user-input inside style tags).
		echo "\n<style id=\"novamira-atomic-styles\">\n"
			. "/* novamira-adrianv2: Atomic CSS workaround for Elementor < 4.2 */\n"
			. implode( "\n", $css_blocks )
			. "\n</style>\n";
	}

	// -------------------------------------------------------------------------
	// Tree walking
	// -------------------------------------------------------------------------

	/**
	 * Recursively walk the Elementor element tree, collecting all
	 * element.styles maps into $all_styles.
	 *
	 * @param array $elements  An array of Elementor element nodes.
	 * @param array $all_styles Accumulated styles map (passed by reference).
	 * @return void
	 */
	private static function collect_styles( array $elements, array &$all_styles ): void {
		foreach ( $elements as $element ) {
			if ( ! is_array( $element ) ) {
				continue;
			}

			// Collect styles from this element's own styles map.
			if ( ! empty( $element['styles'] ) && is_array( $element['styles'] ) ) {
				foreach ( $element['styles'] as $style_id => $style_def ) {
					if ( is_string( $style_id ) && is_array( $style_def ) && ! isset( $all_styles[ $style_id ] ) ) {
						$all_styles[ $style_id ] = $style_def;
					}
				}
			}

			// Recurse into children.
			if ( ! empty( $element['elements'] ) && is_array( $element['elements'] ) ) {
				self::collect_styles( $element['elements'], $all_styles );
			}
		}
	}

	// -------------------------------------------------------------------------
	// CSS rendering
	// -------------------------------------------------------------------------

	/**
	 * Render a style definition to a CSS string.
	 *
	 * @param string $style_id  The key from element.styles (may or may not start with "e-").
	 * @param array  $style_def The style definition with a "variants" array.
	 * @return string One or more CSS rule-blocks (may include @media wrappers).
	 */
	private static function render_style_def( string $style_id, array $style_def ): string {
		// Selector: Elementor adds "e-" prefix to class names in HTML output,
		// so if the style_id doesn't already begin with "e-" we prepend it.
		$css_class    = str_starts_with( $style_id, 'e-' ) ? $style_id : 'e-' . $style_id;
		$base_selector = '.' . $css_class;

		if ( empty( $style_def['variants'] ) || ! is_array( $style_def['variants'] ) ) {
			return '';
		}

		$output = '';
		foreach ( $style_def['variants'] as $variant ) {
			if ( ! is_array( $variant ) ) {
				continue;
			}

			$props = $variant['props'] ?? array();
			if ( ! is_array( $props ) || empty( $props ) ) {
				continue;
			}

			$meta       = is_array( $variant['meta'] ?? null ) ? $variant['meta'] : array();
			$breakpoint = (string) ( $meta['breakpoint'] ?? 'desktop' );
			$state      = isset( $meta['state'] ) && is_string( $meta['state'] ) ? $meta['state'] : null;

			// Build the selector, appending a pseudo-class for states.
			$selector = $base_selector;
			if ( $state && 'normal' !== $state && '' !== $state ) {
				$selector .= ':' . $state;
			}

			// Render declarations.
			$declarations = array();
			foreach ( $props as $prop_name => $prop_value ) {
				if ( ! is_string( $prop_name ) ) {
					continue;
				}
				// Dimensions are special: they expand to multiple logical props.
				if ( is_array( $prop_value ) && ( $prop_value['$$type'] ?? '' ) === 'dimensions' ) {
					$expanded = self::dimensions_to_declarations( $prop_name, $prop_value );
					foreach ( $expanded as $decl ) {
						$declarations[] = '  ' . $decl;
					}
					continue;
				}
				if ( ! is_array( $prop_value ) ) {
					continue;
				}
				$css_value = self::prop_to_css( $prop_value );
				if ( '' !== $css_value ) {
					$declarations[] = '  ' . $prop_name . ': ' . $css_value . ';';
				}
			}

			if ( empty( $declarations ) ) {
				continue;
			}

			$rule = $selector . " {\n" . implode( "\n", $declarations ) . "\n}";

			// Wrap in a media query for responsive variants.
			switch ( $breakpoint ) {
				case 'tablet':
					$rule = "@media (max-width: 1024px) {\n" . $rule . "\n}";
					break;
				case 'mobile':
					$rule = "@media (max-width: 767px) {\n" . $rule . "\n}";
					break;
				// 'desktop' and anything unknown → no wrapper.
			}

			$output .= $rule . "\n";
		}

		return $output;
	}

	// -------------------------------------------------------------------------
	// prop_to_css()
	// -------------------------------------------------------------------------

	/**
	 * Convert a $$type-wrapped Elementor prop to a CSS value string.
	 *
	 * Returns an empty string for prop types that cannot be rendered to CSS
	 * (image attachments, nested structures, unknowns).
	 *
	 * @param array $prop The $$type-wrapped prop array.
	 * @return string A ready-to-use CSS value, or '' if unresolvable.
	 */
	public static function prop_to_css( array $prop ): string {
		$type  = (string) ( $prop['$$type'] ?? '' );
		$value = $prop['value'] ?? null;

		switch ( $type ) {

			// ------------------------------------------------------------------
			// global-color-variable  →  var(--e-gv-{id})
			// The value is a GV identifier like "e-gv-bebd7fa".
			// ------------------------------------------------------------------
			case 'global-color-variable':
				if ( ! is_string( $value ) || '' === $value ) {
					return '';
				}
				// The CSS custom property is --{value}  (value already has the
				// "e-gv-" prefix, e.g. "e-gv-bebd7fa" → "--e-gv-bebd7fa").
				return 'var(--' . $value . ')';

			// ------------------------------------------------------------------
			// color  →  #HEX  (or rgba/hsl as stored)
			// ------------------------------------------------------------------
			case 'color':
				if ( ! is_string( $value ) || '' === $value ) {
					return '';
				}
				return $value;

			// ------------------------------------------------------------------
			// size  →  {n}{unit}   e.g. "16px"
			// Structure: { $$type: "size", value: { size: 16, unit: "px" } }
			// ------------------------------------------------------------------
			case 'size':
				if ( ! is_array( $value ) ) {
					// Fallback: value might be a bare number in older formats.
					if ( is_numeric( $value ) ) {
						return ( (string) $value ) . ( (string) ( $prop['unit'] ?? 'px' ) );
					}
					return '';
				}
				$num  = $value['size'] ?? null;
				$unit = (string) ( $value['unit'] ?? 'px' );
				if ( ! is_numeric( $num ) ) {
					return '';
				}
				// Avoid trailing ".0" for whole numbers.
				$formatted = ( (float) $num === (float) (int) $num )
					? (string) (int) $num
					: rtrim( rtrim( number_format( (float) $num, 4, '.', '' ), '0' ), '.' );
				return $formatted . $unit;

			// ------------------------------------------------------------------
			// dimensions  →  handled separately in dimensions_to_declarations()
			// This branch is reached only if someone calls prop_to_css() directly
			// on a dimensions prop (not via render_style_def).
			// We return a best-effort shorthand here.
			// ------------------------------------------------------------------
			case 'dimensions':
				if ( ! is_array( $value ) ) {
					return '';
				}
				return self::dimensions_shorthand( $value );

			// ------------------------------------------------------------------
			// string  →  raw value (font-family, flex-direction, …)
			// ------------------------------------------------------------------
			case 'string':
				if ( ! is_string( $value ) || '' === $value ) {
					return '';
				}
				return $value;

			// ------------------------------------------------------------------
			// number  →  bare number (z-index, flex-grow, …)
			// ------------------------------------------------------------------
			case 'number':
				if ( ! is_numeric( $value ) ) {
					return '';
				}
				return (string) $value;

			// ------------------------------------------------------------------
			// boolean  →  "true" / "false" (for custom props; rare in CSS)
			// ------------------------------------------------------------------
			case 'boolean':
				return $value ? 'true' : 'false';

			// ------------------------------------------------------------------
			// image-attachment-id, image, url, link, html-v3, classes …
			// Not renderable as a plain CSS value.
			// ------------------------------------------------------------------
			default:
				return '';
		}
	}

	// -------------------------------------------------------------------------
	// Dimensions helpers
	// -------------------------------------------------------------------------

	/**
	 * Expand a `dimensions` prop into individual logical CSS declarations.
	 *
	 * The `dimensions` $$type stores four sides keyed by CSS logical-property
	 * names (block-start, block-end, inline-start, inline-end) or by physical
	 * names (top, right, bottom, left). Each side value is itself a `size`
	 * $$type prop.
	 *
	 * We expand them into individual `{css-prop}-{side}: {value}` declarations
	 * instead of a shorthand so that partial dimensions (e.g. only top set)
	 * work correctly without clobbering the others.
	 *
	 * @param string $css_prop  The CSS property name, e.g. "padding" or "margin".
	 * @param array  $prop      The full $$type-wrapped dimensions prop.
	 * @return string[] Array of "prop-name: value;" declaration strings.
	 */
	private static function dimensions_to_declarations( string $css_prop, array $prop ): array {
		$value = $prop['value'] ?? array();
		if ( ! is_array( $value ) ) {
			return array();
		}

		// Map: stored key → CSS logical-property suffix.
		$side_map = array(
			// Logical names (preferred in V4).
			'block-start'  => '-block-start',
			'block-end'    => '-block-end',
			'inline-start' => '-inline-start',
			'inline-end'   => '-inline-end',
			// Physical names (V3-compat or simple builds).
			'top'    => '-block-start',
			'bottom' => '-block-end',
			'left'   => '-inline-start',
			'right'  => '-inline-end',
		);

		$declarations = array();
		foreach ( $side_map as $key => $suffix ) {
			if ( ! isset( $value[ $key ] ) ) {
				continue;
			}
			$side_prop = $value[ $key ];
			if ( ! is_array( $side_prop ) ) {
				continue;
			}
			$css_value = self::prop_to_css( $side_prop );
			if ( '' !== $css_value ) {
				$declarations[] = $css_prop . $suffix . ': ' . $css_value . ';';
			}
		}

		return $declarations;
	}

	/**
	 * Best-effort shorthand string for a dimensions value (used when
	 * prop_to_css() is called directly on a dimensions prop).
	 *
	 * Returns "top right bottom left" or "block-start inline-end block-end inline-start"
	 * as a space-separated string, e.g. "1rem 2rem 1rem 2rem".
	 *
	 * @param array $value The inner value array of a dimensions prop.
	 * @return string
	 */
	private static function dimensions_shorthand( array $value ): string {
		// Resolve one side: value['block-start'] etc. is a size prop.
		$resolve = function ( string $key ) use ( $value ): string {
			// Try logical name first, then physical fallback.
			$side = $value[ $key ] ?? null;
			if ( is_array( $side ) ) {
				return self::prop_to_css( $side );
			}
			return '0';
		};

		$t = $resolve( 'block-start' ) ?: $resolve( 'top' );
		$r = $resolve( 'inline-end' ) ?: $resolve( 'right' );
		$b = $resolve( 'block-end' ) ?: $resolve( 'bottom' );
		$l = $resolve( 'inline-start' ) ?: $resolve( 'left' );

		if ( '' === $t && '' === $r && '' === $b && '' === $l ) {
			return '';
		}

		$t = $t ?: '0';
		$r = $r ?: '0';
		$b = $b ?: '0';
		$l = $l ?: '0';

		return "{$t} {$r} {$b} {$l}";
	}
}
